#!/bin/bash

set -e
export GPU_COUNT=${GPU_COUNT:-8}                  
export PARTITION=${PARTITION:-"raise"}              
export QUOTA_TYPE=${QUOTA_TYPE:-"reserved"}         

export USE_APPTAINER_FOR_VLLM=${USE_APPTAINER_FOR_VLLM:-true}
export APPTAINER_IMAGE=${APPTAINER_IMAGE:-"./vllm-cu128.sif"}

export MODEL_PATH=${MODEL_PATH:-"./models/Qwen3-VL-8B-Instruct"}
export DATASET_PATH=${DATASET_PATH:-"./data/dataset.json"}
export WORKSPACE_DIR=${WORKSPACE_DIR:-"./workspace"}
export PIL_MAX_IMAGE_PIXELS=${PIL_MAX_IMAGE_PIXELS:-0}       

export ROUND_TOTAL_SAMPLES=${ROUND_TOTAL_SAMPLES:--1}      
export MAX_ROUNDS=${MAX_ROUNDS:-5}                            
export START_ROUND=${START_ROUND:-4}                          
export MANUAL_SKIP_TO_UPGRADE=false
export RESUME_FROM_STEP=1                                    

export ENABLE_SFT=${ENABLE_SFT:-true}                         
export SFT_NUM_TRAIN_EPOCHS=${SFT_NUM_TRAIN_EPOCHS:-3.0}    
export SFT_PER_DEVICE_TRAIN_BATCH_SIZE=${SFT_PER_DEVICE_TRAIN_BATCH_SIZE:-1}  
export SFT_GRADIENT_ACCUMULATION_STEPS=${SFT_GRADIENT_ACCUMULATION_STEPS:-2} 
export SFT_LEARNING_RATE=${SFT_LEARNING_RATE:-5e-6}       
export SFT_WARMUP_RATIO=${SFT_WARMUP_RATIO:-0.1}            
export SFT_LR_SCHEDULER_TYPE=${SFT_LR_SCHEDULER_TYPE:-cosine}  
export SFT_LOGGING_STEPS=${SFT_LOGGING_STEPS:-10}            
export SFT_SAVE_STEPS=${SFT_SAVE_STEPS:-100}                
export SFT_CUTOFF_LEN=${SFT_CUTOFF_LEN:-10240}               
export SFT_FREEZE_VISION_TOWER=${SFT_FREEZE_VISION_TOWER:-true}   
export SFT_FREEZE_PROJECTOR=${SFT_FREEZE_PROJECTOR:-true}      
export SFT_FREEZE_LLM=${SFT_FREEZE_LLM:-false}                     
export SFT_LR_FIRST_ROUND=${SFT_LR_FIRST_ROUND:-5e-6}
export SFT_LR_OTHER_ROUNDS=${SFT_LR_OTHER_ROUNDS:-1e-5}
export SFT_ENABLE_PACKING=${SFT_ENABLE_PACKING:-true}

export ENABLE_HES_FILTERING=${ENABLE_HES_FILTERING:-true}        
export HES_TOP_RATIO=${HES_TOP_RATIO:-0.2}                     
export HES_PERCENTILE_CUTOFF=${HES_PERCENTILE_CUTOFF:-0.005}     
export HES_BATCH_SIZE=${HES_BATCH_SIZE:-8}                   
export HES_TENSOR_PARALLEL_SIZE=${HES_TENSOR_PARALLEL_SIZE:-8}  

export DPO_MEMORY_WAIT_TIME=${DPO_MEMORY_WAIT_TIME:-20}     

export USE_LLM_JUDGE=${USE_LLM_JUDGE:-true}
export JUDGE_MODEL_PATH=${JUDGE_MODEL_PATH:-"./models/Qwen3-30B-A3B-Instruct-2507"}
export JUDGE_TENSOR_PARALLEL_SIZE=${JUDGE_TENSOR_PARALLEL_SIZE:-8} 
export JUDGE_GPU_MEMORY_UTILIZATION=${JUDGE_GPU_MEMORY_UTILIZATION:-0.6}
export JUDGE_MAX_MODEL_LEN=${JUDGE_MAX_MODEL_LEN:-65536}     

export USE_LLM_GENERATOR=${USE_LLM_GENERATOR:-true}
export LLM_GENERATOR_MODEL_PATH=${LLM_GENERATOR_MODEL_PATH:-"./models/Qwen3-VL-235B-A22B-Thinking"}
export LLM_GENERATOR_TENSOR_PARALLEL_SIZE=${LLM_GENERATOR_TENSOR_PARALLEL_SIZE:-8}  
export LLM_GENERATOR_GPU_MEMORY_UTILIZATION=${LLM_GENERATOR_GPU_MEMORY_UTILIZATION:-0.8}  
export LLM_GENERATOR_MAX_MODEL_LEN=${LLM_GENERATOR_MAX_MODEL_LEN:-32768}  
export EVAL_TEMPERATURE=${EVAL_TEMPERATURE:-0.0}
export EVAL_TOP_P=${EVAL_TOP_P:-1.0}
export EVAL_MAX_TOKENS=${EVAL_MAX_TOKENS:-16384}  
export EVAL_FREQUENCY_PENALTY=${EVAL_FREQUENCY_PENALTY:-0}  
export EVAL_TENSOR_PARALLEL_SIZE=${EVAL_TENSOR_PARALLEL_SIZE:-8}  
export CORRECTED_COT_MAX_TOKENS=${CORRECTED_COT_MAX_TOKENS:-32768} 
export GEMINI_API_KEY=${GEMINI_API_KEY:-""}
export GEMINI_MODEL=${GEMINI_MODEL:-"gemini-3-flash-preview-thinking"}
export GEMINI_BASE_URL=${GEMINI_BASE_URL:-""}
export GEMINI_MAX_TOKENS=${GEMINI_MAX_TOKENS:-65536}              
export GEMINI_MAX_OUTPUT_TOKENS=${GEMINI_MAX_OUTPUT_TOKENS:-65536} 
export CORRECTED_COT_API_KEY=${CORRECTED_COT_API_KEY:-""}
export CORRECTED_COT_MODEL=${CORRECTED_COT_MODEL:-"qwen3-vl-235b-a22b-thinking"}
export CORRECTED_COT_BASE_URL=${CORRECTED_COT_BASE_URL:-""}
export CORRECTED_COT_MAX_WORKERS=${CORRECTED_COT_MAX_WORKERS:-30} 
export ENABLE_ERROR_ANALYSIS=${ENABLE_ERROR_ANALYSIS:-true}
export ERROR_ANALYZER_MODEL_PATH=${ERROR_ANALYZER_MODEL_PATH:-"./models/Qwen3-VL-30B-A3B-Thinking"}
export ERROR_ANALYZER_TENSOR_PARALLEL_SIZE=${ERROR_ANALYZER_TENSOR_PARALLEL_SIZE:-8} 
export ERROR_ANALYZER_GPU_MEMORY_UTILIZATION=${ERROR_ANALYZER_GPU_MEMORY_UTILIZATION:-0.75} 
export ERROR_ANALYZER_MAX_MODEL_LEN=${ERROR_ANALYZER_MAX_MODEL_LEN:-65536} 
export ERROR_ANALYZER_MAX_TOKENS=${ERROR_ANALYZER_MAX_TOKENS:-8192}  
# Change to your project directory
# cd /path/to/your/project
LOG_DIR="$WORKSPACE_DIR/logs"
mkdir -p $LOG_DIR
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="$LOG_DIR/adaptive_train_dpo_${TIMESTAMP}.log"

python -m adaptive_training


